Workspace for Espressif's SoC development on Zephyr update
LucasTambor/EspZephyrWS pull request #1
Opened 2024-10-10 17:47 UTC by wmrsouza

Workspace for Espressif's SoC development on Zephyr update:
- toolchain version
- .svd files
- ESP32C2 workspace added

2024-10-10 18:28 UTC, LucasTambor requested changes
Niice

2024-10-10 18:28 UTC, LucasTambor commented on .vscode/launch.json
>  		// "runToEntryPoint": "main"
Can you remove the commented code?

2024-10-10 18:28 UTC, LucasTambor commented on .vscode/launch.json
> +			//"thb __start",
ditto

2024-10-10 18:28 UTC, LucasTambor commented on .vscode/launch.json
> +		//"showDevDebugOutput": "raw",
ditto

2024-10-11 23:38 UTC, wmrsouza commented
@LucasTambor

2024-10-15 13:30 UTC, LucasTambor approved these changes

2024-10-15 13:31 UTC, merged